lang update

diff --git a/scripts/console/pull_oxide_lang b/scripts/console/pull_oxide_lang
--- a/scripts/console/pull_oxide_lang
+++ b/scripts/console/pull_oxide_lang
@@ -1,11 +1,36 @@
 #!/bin/bash
 SERVER=$1
 PLUGIN=$2
-REPO_DIR="/c/Users/shaun/repos/solidrust.net/defaults"
-SERVER_KEYS="/c/Users/shaun/repos"
+LANG=(cs
+de
+en
+es
+fr
+nl
+pt-BR
+ru
+zh-CN)
+
+if [ -z "${SRT_REPO}" ]; then
+  echo "SRT_REPO ver is not configured, using defaults."
+  export SRT_REPO="${HOME}/repos/solidrust.net"
+fi
+echo "Using repo from: ${SRT_REPO} ."
+echo "Checking for SERVER_KEYS in: ${SERVER_KEYS} ."
+if [ -z "${SERVER_KEYS}" ]; then
+  export SERVER_KEYS="/c/Users/shaun/repos"
+  echo "No SERVER_KEYS var defined, using default of ${SERVER_KEYS} ."
+else
+  echo "SERVER_KEYS successfully located in: ${SERVER_KEYS} ."
+fi
+
+function usage_helper() {
+  echo ""
+  echo "Usage: pull_oxide_lang <server> <plugin_name|all>"
+  echo ""
+}
 
 case $SERVER in
-
   nine)
     SCP_CMD="scp -i ${SERVER_KEYS}/us-west-2-solidrust.pem admin@nine.solidrust.net"
     ;;
@@ -13,14 +38,43 @@ case $SERVER in
     SCP_CMD="scp -i ${SERVER_KEYS}/solidrust-us-east-1pem.pem admin@demo.solidrust.net"
     ;;
   *)
-    echo "pull_data: Invalid server selection"
+    echo "pull: Invalid server selection"
     echo ""
-    echo "Currently supported server(s): nine"
+    echo "Currently supported server(s): nine, demo"
     echo ""
-    echo "Usage: pull_data <server> <plugin>"
-    echo ""
+    usage_helper
+    exit 1
     ;;
 esac
 
-echo "Pulling ${PLUGIN} languages from ${SERVER}"
-$SCP_CMD:/game/oxide/lang/en/${PLUGIN}.json "${REPO_DIR}/oxide/lang/en/"
+if [ -z "${PLUGIN}" ]; then
+  echo "pull: no plugin selection detected"
+  echo ""
+  echo "Please specify a plugin to pull from, such as 'AutoDoors'"
+  usage_helper
+  exit 1
+else
+  case ${PLUGIN} in
+  all)
+    echo "do it for Dale"
+    ${SSH_CMD} "cd /game/oxide/plugins; ls -1 *.cs | rev | cut -c4- | rev > /tmp/solidrust_plugins.list"
+    ${SCP_CMD}:/tmp/solidrust_plugins.list "${SRT_REPO}/servers/${SERVER}/"
+    for plugin in $(cat "${SRT_REPO}/servers/${SERVER}/solidrust_plugins.list"); do
+      echo "Doin the $plugin plugin"
+      for lang in ${LANG[@]}; do
+        echo "Pulling $lang language files..."
+        $SCP_CMD:/game/oxide/lang/$lang/${plugin}.json "${SRT_REPO}/defaults/oxide/lang/$lang/"
+      done
+    done
+    ;;
+  *)
+    echo "Configured destination: ${SRT_REPO}/defaults/oxide/config/"
+    echo "Pulling ${PLUGIN} config from ${SERVER}"
+    for lang in ${LANG[@]}; do
+      echo "Pulling $lang language files..."
+      $SCP_CMD:/game/oxide/lang/$lang/${PLUGIN}.json "${SRT_REPO}/defaults/oxide/lang/$lang/"
+    done
+    ;;
+  esac
+fi
+echo "Done!"
